version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    ports:
      - "9510:9510"  # FastAPI application
      - "9610:9610"  # MLflow UI
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_ARTIFACTS_DESTINATION=/mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts

volumes:
  mlflow_artifacts:

networks:
  mlflow-network:
    driver: bridge